name: Continuous Integration
on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  CI_Build_And_Test:
    name: CI Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test

  CD_Publish:
    name: CD Publish
    if: ${{ github.ref == 'refs/heads/dev/Module8-ProjectExercise' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [CI_Build_And_Test]
    steps:
    - uses: actions/checkout@v2
    - run: echo "Publishing!"