name: Continuous Integration
on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  CI_Build_And_Test:
    name: CI Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: docker build --target test --tag todo-app:test .

    - name: Docker run tests
      run: docker run todo-app:test

  CD_Publish_Docker_Hub:
    name: CD Publish to Docker Hub
    if: ${{ (github.ref == 'refs/heads/dev/Module8-ProjectExercise' || github.ref == 'refs/heads/main') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [CI_Build_And_Test]
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build --target production --tag todo-app:prod .

    - name: Tag Docker image
      run: docker tag todo-app:prod cuffindall/todo-app:$GITHUB_SHA

    - name: Publish to Docker Hub
      run: docker push cuffindall/todo-app:$GITHUB_SHA

  CD_Deploy_Heroku:
    name: CD Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [CD_Publish_Docker_Hub]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "cu-todo-app" #Must be unique in Heroku
          heroku_email: "craig.uffindall@necsws.com"
          usedocker: true